//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PAPER_CHECKSHEET
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHECKSHEET
    {
        public int ID { get; set; }
        public string Customer { get; set; }
        public string Model { get; set; }
        public string MaLinhKien { get; set; }
        public string WO { get; set; }
        public int QTY { get; set; }
        public string CodeUser { get; set; }
        public string CodeConfirm { get; set; }
        public System.DateTime Dat { get; set; }
        public string Machine { get; set; }
        public string MachineCode { get; set; }
        public string JigCode { get; set; }
        public System.DateTime ModifyDate { get; set; }
    }
}
