//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PAPER_CHECKSHEET
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHECKSHEET_DETAIL
    {
        public int ID { get; set; }
        public int IdCheckSheet { get; set; }
        public int Number { get; set; }
        public string Spec { get; set; }
        public double SpecValue { get; set; }
    }
}
