//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PAPER_CHECKSHEET
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class E_CHECKSHEETEntities : DbContext
    {
        public E_CHECKSHEETEntities()
            : base("name=E_CHECKSHEETEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CHECKSHEET_DETAIL> CHECKSHEET_DETAIL { get; set; }
        public virtual DbSet<MALINHKIEN> MALINHKIENs { get; set; }
        public virtual DbSet<MODEL> MODELs { get; set; }
        public virtual DbSet<SPEC_SETTING> SPEC_SETTING { get; set; }
        public virtual DbSet<CUSTOMER> CUSTOMERs { get; set; }
        public virtual DbSet<CHECKSHEET_DETAIL_HIS> CHECKSHEET_DETAIL_HIS { get; set; }
        public virtual DbSet<CHECKSHEET> CHECKSHEETs { get; set; }
        public virtual DbSet<CHECKSHEET_HIS> CHECKSHEET_HIS { get; set; }
    }
}
