//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PAPER_CHECKSHEET
{
    using System;
    using System.Collections.Generic;
    
    public partial class SPEC_SETTING
    {
        public int ID { get; set; }
        public string Model { get; set; }
        public string MaLinhKien { get; set; }
        public string Spec { get; set; }
        public double Min { get; set; }
        public double Max { get; set; }
    }
}
